import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "CGGeIBsuWWU",
    video_title: "AS a Final Act of love",
    video_description: `This video is created when i was heartbroken and i was trying to express my feelings through this video. I hope you will like it.`,
    tags: ["LoveFAANG Career", "Heartbreak", " Emotional",],
    cover_image: "CGGeIBsuWWU",
    publish_date: "2025-11-27",
    client_name: "Naimur rahman",
    client_image: "/companies/growthleo.png",

    client_feedback: "",
    video_link: "https://youtu.be/CGGeIBsuWWU?si=CGGeIBsuWWU",
    project_images: [],
    category: ["Talking Head", "ALL", 'Explainer'],
    duration: "23sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "S1gb7ugYJO4",
    video_title: "Are you looking for a video editor?",
    video_description: `This video is created for a client who was looking for a video editor. I have edited this video for them and they were satisfied with my work.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "S1gb7ugYJO4",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=S1gb7ugYJO4",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "4:59",
    software_used: ["Premiere Pro", "After Effects"],
  },

// Shorts


  {
    id: "7FECfBBUKzE",
    video_title: "The cyber security",
    video_description: "Cybersecurity is the practice of protecting computers, networks, programs, and data from digital attacks, damage, or unauthorized access",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "7FECfBBUKzE",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/7FECfBBUKzE",
    project_images: [],
    category: ["Shorts", "UGC Shorts"],
    duration: "59sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
    {
    id: "b1dqIz6Rnm4",
    video_title: "Getting Your First Deal",
    video_description: "Securing your first real estate deal requires finding a distressed property, building a cash buyer list, and locking the property under contract using an Assignment Contract Guide or standard purchase agreement",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "b1dqIz6Rnm4",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/b1dqIz6Rnm4",
    project_images: [],
    category: ["Shorts", "UGC Shorts"],
    duration: "47:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "0tFIJvIlsAY",
    video_title: "What is your mindset?",
    video_description: "The best mindset to have is a growth mindset paired with adaptability and self-belief, as explored in insights on Verywell Mind. This approach helps you see challenges as chances to learn rather than reasons to quit",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "0tFIJvIlsAY",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/0tFIJvIlsAY",
    project_images: [],
    category: ["Shorts", "UGC Shorts"],
    duration: "40:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
// UGC Shorts
   {
    id: "FtTNACGa890",
    video_title: "Before i was Finance Angel",
    video_description: "Finance is the study and management of how people, businesses, and governments make, spend, save, and borrow money. It helps people build secure futures and allows companies to grow",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "FtTNACGa890",
    publish_date: "2026-09-18",
    client_name: "Maria",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/FtTNACGa890",
    project_images: [],
    category: ["Shorts",'UGC Shorts'],
    duration: "42:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "-Y1pqDx50LM",
    video_title: "You are already successfull",
    video_description: "Real success is an inner state of peace and growth. You reach success when you stop chasing what others want and start valuing your own daily progress",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "-Y1pqDx50LM",
    publish_date: "2026-09-18",
    client_name: "Maria",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/-Y1pqDx50LM",
    project_images: [],
    category: ["Shorts",'UGC Shorts'],
    duration: "43:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },

// UGC Shorts

//  AI FACELESS 
  {
    id: "Ap66hV0qr-U",
    video_title: "The Kettlebell Prying Squad",
    video_description: "The kettlebell prying squat is a dynamic mobility and strength exercise where you hold a kettlebell at your chest, sink into the bottom of a deep squat, and use your elbows to gently push your knees apart while shifting side to side to open up tight hips and ankles",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "Ap66hV0qr-U",
    publish_date: "2026-07-18",
    client_name: "Liftzip",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=Ap66hV0qr-U",
    project_images: [],
    category: ["AI Faceless",],
    duration: "7:45min",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "MnoDI1sdodA",
    video_title: "Farmers walk kettlebell",
    video_description: "A kettlebell farmer walk is a simple, powerful full-body exercise where you hold a heavy kettlebell in each hand and walk forward. It builds massive grip strength, locks in your core, and fixes your posture while also improving your cardiovascular fitness. It’s a great exercise for building strength, endurance, and stability.",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "MnoDI1sdodA",
    publish_date: "2026-07-28",
    client_name: "Liftzip",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=MnoDI1sdodA",
    project_images: [],
    category: ["AI Faceless",],
    duration: "8:49min",
    software_used: ["Premiere Pro", "After Effects"],
  },
 
   {
    id: "5BnxuQ4LU50",
    video_title: "These 5 Kettlebell Exercises",
    video_description: "A kettlebell is a cast-iron or steel ball with a handle used to perform ballistic, strength, and flexibility exercises. It builds total-body power, core stability, and cardio endurance through dynamic movements.",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "5BnxuQ4LU50",
    publish_date: "2026-07-28",
    client_name: "Liftzip",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=5BnxuQ4LU50",
    project_images: [],
    category: ["AI Faceless",],
    duration: "6:09min",
    software_used: ["Premiere Pro", "After Effects"],
  },
   {
    id: "819cpmFgUio",
    video_title: "Turkish get off kettlebell",
    video_description: "The kettlebell Turkish get-up is a total-body functional movement that transitions you from lying flat on the floor to standing completely upright while holding a weight overhead.",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "819cpmFgUio",
    publish_date: "2026-08-28",
    client_name: "Liftzip",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=819cpmFgUio",
    project_images: [],
    category: ["AI Faceless",],
    duration: "3:50min",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "KX7wa-GeeWI",
    video_title: "Suitcase Carry Kettlebell single hand",
    video_description: "The suitcase carry involves holding a kettlebell by your side and walking while engaging your core, like you would if you were carrying a suitcase, hence the name. Add it to your total-body workout to boost your overall strength",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "KX7wa-GeeWI",
    publish_date: "2026-09-4",
    client_name: "Liftzip",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=KX7wa-GeeWI",
    project_images: [],
    category: ["AI Faceless",],
    duration: "4:00min",
    software_used: ["Premiere Pro", "After Effects"],
  },
//  AI FACELESS 

];


