import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "CGGeIBsuWWU",
    video_title: "AS a Final Act of love",
    video_description: `This video is created when i was heartbroken and i was trying to express my feelings through this video. I hope you will like it.`,
    tags: ["LoveFAANG Career", "Heartbreak", " Emotional",],
    cover_image: "CGGeIBsuWWU",
    publish_date: "2025-11-27",
    client_name: "Naimur rahman",
    client_image: "/companies/growthleo.png",

    client_feedback: "",
    video_link: "https://youtu.be/CGGeIBsuWWU?si=CGGeIBsuWWU",
    project_images: [],
    category: ["Talking Head", "ALL", 'Explainer'],
    duration: "23sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "S1gb7ugYJO4",
    video_title: "Are you looking for a video editor?",
    video_description: `This video is created for a client who was looking for a video editor. I have edited this video for them and they were satisfied with my work.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "S1gb7ugYJO4",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=S1gb7ugYJO4",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "4:59",
    software_used: ["Premiere Pro", "After Effects"],
  },

// Shorts


  {
    id: "7FECfBBUKzE",
    video_title: "The cyber security",
    video_description: "Cybersecurity is the practice of protecting computers, networks, programs, and data from digital attacks, damage, or unauthorized access",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "7FECfBBUKzE",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/7FECfBBUKzE",
    project_images: [],
    category: ["Shorts", ""],
    duration: "59sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
    {
    id: "b1dqIz6Rnm4",
    video_title: "Getting Your First Deal",
    video_description: "Securing your first real estate deal requires finding a distressed property, building a cash buyer list, and locking the property under contract using an Assignment Contract Guide or standard purchase agreement",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "b1dqIz6Rnm4 ",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/b1dqIz6Rnm4",
    project_images: [],
    category: ["Shorts", ""],
    duration: "47:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "0tFIJvIlsAY",
    video_title: "What is your mindset?",
    video_description: "The best mindset to have is a growth mindset paired with adaptability and self-belief, as explored in insights on Verywell Mind. This approach helps you see challenges as chances to learn rather than reasons to quit",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "0tFIJvIlsAY ",
    publish_date: "2026-09-18",
    client_name: "Growthleo",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/0tFIJvIlsAY",
    project_images: [],
    category: ["Shorts", ""],
    duration: "40:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
// UGC Shorts
   {
    id: "FtTNACGa890",
    video_title: "Before i was Finance Angel",
    video_description: "Finance is the study and management of how people, businesses, and governments make, spend, save, and borrow money. It helps people build secure futures and allows companies to grow",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "FtTNACGa890 ",
    publish_date: "2026-09-18",
    client_name: "Maria",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/FtTNACGa890",
    project_images: [],
    category: ["Shorts",'UGC Shorts'],
    duration: "42:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "-Y1pqDx50LM",
    video_title: "You are already successfull",
    video_description: "Real success is an inner state of peace and growth. You reach success when you stop chasing what others want and start valuing your own daily progress",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "-Y1pqDx50LM ",
    publish_date: "2026-09-18",
    client_name: "Maria",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/-Y1pqDx50LM",
    project_images: [],
    category: ["Shorts",'UGC Shorts'],
    duration: "43:00sec",
    software_used: ["Premiere Pro", "After Effects"],
  },

// UGC Shorts

 

];


